/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481_hw1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {


  @Test
  public void testInvalidLimit() {
    ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
    ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(2, 3, 3, 4));
    assertTrue(App.compareArraysElementByElement(array2, array, -2));
  }

    @Test
    public void testNull(){
      ArrayList<Integer> arr = new ArrayList<>();
      arr.add(1); arr.add(1); arr.add(1);
      assertFalse(App.compareArraysElementByElement((null), arr, 1));
    }
    @Test
    public void testEmptyArray(){
      ArrayList<Integer> empty = new ArrayList<>();
      ArrayList<Integer> arr = new ArrayList<>();
      arr.add(1); arr.add(1); arr.add(1);
      assertFalse(App.compareArraysElementByElement(empty, arr, 1));
    }

    @Test
    public void testSuitableForLimit() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(2, 3, 3, 4));
      assertTrue(App.compareArraysElementByElement(array2, array, 2));
    }

    @Test
    public void testNotSuitableForLimit() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(3, 4, 5, 6));
      assertFalse(App.compareArraysElementByElement(array2, array, 2));
    }


}
